# Generated by Django 5.1.3 on 2024-11-11 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('view_future_events', 'Can view future events'), ('view_past_events', 'Can view past events'), ('view_all_events', 'Can view all events'), ('edit_all_events', 'Can edit all events'), ('delete_all_events', 'Can delete all events')]},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'permissions': [('view_future_reservations', 'Can view future reservations'), ('view_past_reservations', 'Can view past reservations'), ('view_all_reservations', 'Can view all reservations'), ('edit_all_reservations', 'Can edit all reservations'), ('delete_all_reservations', 'Can delete all reservations')]},
        ),
    ]
