services:
  db:
    image: postgres:14.8-alpine3.18
    volumes:
      - .docker/.volumes/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app/
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - "8080:8080"
    depends_on:
      - db
